### PR TITLE
jsonata v1.6.4

### PR DESCRIPTION
**Pull request by zuker**

### CODE REVIEW

**Comment by jhorbulyk** [comment]
Have we run into this issue at all? https://github.com/jsonata-js/jsonata/issues/314

**Comment by zuker** [comment]
@jhorbulyk we are going to QA this version in mapper component and front.

**Comment by zubairov** [comment]
looks like a showstopper for migration for us, what do you think?

**Comment by jhorbulyk** [comment]
> looks like a showstopper for migration for us, what do you think?

My impression is that it would be but we can allow testing to determine this for certain.

**Comment by zuker** [comment]
i think showstopper is TravisCI, i hope it will build it finally next week at least.

**Pull request merged**
